import { GoogleGenAI } from "@google/genai";

const MAX_RETRIES = 3;
const RETRY_DELAY = 1000; // 1 second

export interface AIResponse {
  text: string;
  error?: string;
}

/**
 * Validates input text for AI generation
 */
const validateInput = (text: string): string | null => {
  if (!text || text.trim().length < 10) {
    return "Input is too short. Please provide more details.";
  }
  if (text.length > 5000) {
    return "Input is too long. Please shorten your text.";
  }
  // Basic check for suspicious characters if needed
  return null;
};

/**
 * Simple sleep function for retries
 */
const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Centralized AI Service for Gemini API calls
 */
export const aiService = {
  /**
   * Generates content using Gemini with retries and validation
   */
  generateContent: async (prompt: string, systemInstruction?: string): Promise<AIResponse> => {
    const validationError = validateInput(prompt);
    if (validationError) {
      return { text: '', error: validationError };
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return { text: '', error: "AI Service is currently unavailable (API Key missing)." };
    }

    const ai = new GoogleGenAI({ apiKey });
    let lastError: any;

    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
      try {
        const response = await ai.models.generateContent({
          model: "gemini-2.5-flash",
          contents: prompt,
          config: systemInstruction ? { systemInstruction } : undefined,
        });

        const text = response.text;
        if (text) {
          return { text };
        }
        throw new Error("No content generated by AI.");
      } catch (err: any) {
        lastError = err;
        console.warn(`AI Generation attempt ${attempt} failed:`, err.message);
        
        // Don't retry on certain errors (e.g., safety, invalid key)
        if (err.message?.includes("API key not valid") || err.message?.includes("SAFETY")) {
          break;
        }

        if (attempt < MAX_RETRIES) {
          await sleep(RETRY_DELAY * attempt);
        }
      }
    }

    return { 
      text: '', 
      error: `Failed to generate content after ${MAX_RETRIES} attempts. ${lastError?.message || 'Please try again later.'}` 
    };
  }
};
