import React, { useState, useEffect } from "react";
import { Sparkles, Loader2, Check, RefreshCw } from "lucide-react";
import { motion } from "motion/react";
import { useLanguageStore } from "../../store/useLanguageStore";
import { aiService } from "../../services/aiService";

// Beautiful Typewriter Effect component with blinking AI cursor
function TypewriterText({ text, speed = 10 }: { text: string; speed?: number }) {
  const [displayedText, setDisplayedText] = useState("");
  const [isTyping, setIsTyping] = useState(true);

  useEffect(() => {
    setDisplayedText("");
    setIsTyping(true);
    let index = 0;
    const interval = setInterval(() => {
      // safe bounds check
      if (index < text.length) {
        setDisplayedText((prev) => prev + text.charAt(index));
        index++;
      } else {
        clearInterval(interval);
        setIsTyping(false);
      }
    }, speed);

    return () => clearInterval(interval);
  }, [text, speed]);

  return (
    <span className="relative">
      {displayedText}
      {isTyping && (
        <span className="inline-block w-1.5 h-3.5 ml-0.5 bg-[#001639] animate-pulse" style={{ verticalAlign: 'middle' }} />
      )}
    </span>
  );
}

interface AISuggestionProps {
  currentValue: string;
  onApply: (newValue: string) => void;
  context?: string;
  promptOverride?: string;
}

const CHIPS: Record<string, { id: 'professional' | 'shorten' | 'translate'; label: string; emoji: string }[]> = {
  ar: [
    { id: "professional", label: "صياغة احترافية", emoji: "✨" },
    { id: "shorten", label: "اختصار النص", emoji: "✍️" },
    { id: "translate", label: "ترجمة للإنجليزية", emoji: "🌐" },
  ],
  en: [
    { id: "professional", label: "Professional Polish", emoji: "✨" },
    { id: "shorten", label: "Shorten Text", emoji: "✍️" },
    { id: "translate", label: "To English", emoji: "🌐" },
  ],
  fr: [
    { id: "professional", label: "Formulation Pro", emoji: "✨" },
    { id: "shorten", label: "Rendre Concis", emoji: "✍️" },
    { id: "translate", label: "En Anglais", emoji: "🌐" },
  ],
};

export default function AISuggestion({
  currentValue,
  onApply,
  context,
  promptOverride,
}: AISuggestionProps) {
  const { language } = useLanguageStore();
  const [isGenerating, setIsGenerating] = useState(false);
  const [suggestion, setSuggestion] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [activeChip, setActiveChip] = useState<'professional' | 'shorten' | 'translate' | null>(null);

  const generateSuggestion = async (style?: 'professional' | 'shorten' | 'translate') => {
    if (!currentValue.trim() && !promptOverride) return;

    setIsGenerating(true);
    setError(null);
    if (style) {
      setActiveChip(style);
    }

    try {
      let prompt = promptOverride;
      if (!prompt) {
        let styleInstruction = "Improve the following sentence for a resume to make it more impactful, professional, and result-oriented. If possible, turn it into a numerical achievement.";
        if (style === "shorten") {
          styleInstruction = "Condense the following resume accomplishment to make it extremely clear, brief, and concise. Ideal for a resume bullet point.";
        } else if (style === "translate") {
          styleInstruction = "Translate the following resume accomplishment to highly professional English suitable for an ATS-optimized CV.";
        } else if (style === "professional") {
          styleInstruction = "Re-write the following resume text using strong action verbs, professional tone, and results-focused phrasing.";
        }

        const targetLang = style === "translate" ? "English" : (language === "ar" ? "Arabic" : language === "fr" ? "French" : "English");

        prompt = `
You are an expert professional CV writer.
Follow this instruction: ${styleInstruction}
Target Language: ${targetLang}.

Current text: "${currentValue}"
Context (if any): "${context || ""}"

Provide ONLY the final improved sentence, with absolutely no notes, no chat/message prefixes (like "Here is the improved sentence..."), and no double quotes around it.
`;
      }

      const response = await aiService.generateContent(prompt);

      const text = response.text?.trim();
      if (text) {
        // Strip out enclosing quotes if generated by AI
        let formattedText = text;
        if (formattedText.startsWith('"') && formattedText.endsWith('"')) {
          formattedText = formattedText.slice(1, -1);
        }
        setSuggestion(formattedText);
      } else {
        setError(response.error || "Could not generate suggestion");
      }
    } catch (err) {
      console.error("AI Suggestion Error:", err);
      setError("Error connecting to AI");
    } finally {
      setIsGenerating(false);
    }
  };

  if (!currentValue.trim() && !promptOverride) return null;

  const currentChips = CHIPS[language] || CHIPS.en;

  return (
    <div className="mt-3 p-4 rounded-2xl bg-slate-50 border border-slate-200 shadow-3xs">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-3">
        <div className="flex items-center gap-1.5 text-[#001639]">
          <Sparkles size={14} className="animate-pulse" />
          <span className="text-[10px] font-black uppercase tracking-wider">
            {language === "ar" ? "مساعد الذكاء الاصطناعي السريع" : "AI Quick Assistant"}
          </span>
        </div>
        {!suggestion && !isGenerating && (
          <button
            onClick={() => generateSuggestion()}
            className="text-[11px] font-bold text-slate-600 hover:text-slate-900 transition-colors"
          >
            {language === "ar"
              ? "تحسين تلقائي 🪄"
              : "Auto Improve 🪄"}
          </button>
        )}
      </div>

      {/* Speed chips */}
      {!suggestion && !isGenerating && (
        <div className="flex flex-wrap gap-1.5 mb-1.5">
          {currentChips.map((chip) => (
            <button
              key={chip.id}
              onClick={() => generateSuggestion(chip.id)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-slate-200/60 bg-white hover:bg-[#001639]/5 hover:border-[#001639]/20 text-[11px] font-bold text-slate-705 shadow-3xs transition-all cursor-pointer scale-100 active:scale-95 duration-150"
            >
              <span>{chip.emoji}</span>
              <span>{chip.label}</span>
            </button>
          ))}
        </div>
      )}

      {isGenerating && (
        <div className="space-y-3 py-2">
          <div className="flex items-center gap-2">
            <Loader2 size={12} className="animate-spin text-[#001639]" />
            <span className="text-xs text-slate-500 italic font-medium">
               {language === "ar" ? "جاري الصياغة والتحسين..." : "Drafting & Polishing..."}
            </span>
          </div>
          <div className="space-y-2">
            <motion.div 
               animate={{ opacity: [0.3, 0.6, 0.3] }}
               transition={{ repeat: Infinity, duration: 1.5 }}
               className="h-2.5 bg-slate-200 rounded-full w-full" 
            />
            <motion.div 
               animate={{ opacity: [0.3, 0.6, 0.3] }}
               transition={{ repeat: Infinity, duration: 1.5, delay: 0.2 }}
               className="h-2.5 bg-slate-200 rounded-full w-5/6" 
            />
          </div>
        </div>
      )}

      {suggestion && (
        <div className="space-y-2.5 bg-white p-3 rounded-xl border border-slate-150 shadow-3xs">
          <p className="text-xs sm:text-sm text-slate-800 font-medium leading-relaxed">
            "
            <TypewriterText text={suggestion} />
            "
          </p>
          <div className="flex gap-2">
            <button
              onClick={() => {
                onApply(suggestion);
                setSuggestion(null);
                setActiveChip(null);
              }}
              className="flex items-center gap-1 px-3 py-1.5 bg-slate-900 hover:bg-black text-white rounded-lg text-xs font-bold transition-all cursor-pointer"
            >
              <Check size={12} />
              {language === "ar" ? "تطبيق التعديل" : "Apply Improvement"}
            </button>
            <button
              onClick={() => generateSuggestion(activeChip || undefined)}
              className="flex items-center gap-1 px-3 py-1.5 bg-slate-50 text-slate-600 border border-slate-200 hover:bg-slate-100 rounded-lg text-xs font-bold transition-all cursor-pointer"
            >
              <RefreshCw size={12} />
              {language === "ar" ? "إعادة المحاولة" : "Retry"}
            </button>
          </div>
        </div>
      )}

      {error && (
        <p className="text-[10px] text-rose-500 font-medium">{error}</p>
      )}
    </div>
  );
}
